spring:
  application.name: server
  datasource:
    url: jdbc:h2:mem:messasync
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true