spring:
  application.name: server
  datasource:
    url: jdbc:h2:mem:messasync
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: gemma3:4b
